solution modal
js-tasks-ru/htmlcss-20220519_trapjkeeee pull request #11
Opened 2022-05-31 13:20 UTC by TrapJkeee

2022-05-31 13:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-03 18:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-10 18:43 UTC, GSemikozov requested changes

2022-06-10 18:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
у нас уже есть блок Кнопка, просто нужно подключить на страницу файл стилей, и ни в коем случае не дублировать то что уже есть и не описывать одни блоки в других

2022-06-10 18:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
fixed

2022-06-10 18:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
а вот тут - absolute )

2022-06-10 18:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
absolute

2022-06-11 18:27 UTC, TrapJkeee commented on 05-lection3/02-modal/modal.css
> +.button {
об этом я даже и не подумал) +

2022-06-11 18:27 UTC, TrapJkeee commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
+

2022-06-11 18:27 UTC, TrapJkeee commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
"+"

2022-06-13 06:26 UTC, TrapJkeee commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
"+"

2022-06-14 14:17 UTC, GSemikozov approved these changes

2022-06-14 14:17 UTC, merged