solution radio
js-tasks-ru/htmlcss-20220519_trapjkeeee pull request #17
Opened 2022-06-07 14:51 UTC by TrapJkeee

2022-06-07 14:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-09 04:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-09 04:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-09 04:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-09 04:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-10 04:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-11 17:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-11 18:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-13 10:46 UTC, GSemikozov requested changes

2022-06-13 10:46 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    font-family: 'Inter';
не нужно дублировать все стили, просто content

2022-06-14 15:05 UTC, closed without merging