solution accordion
js-tasks-ru/htmlcss-20220519_trapjkeeee pull request #4
Opened 2022-05-27 04:28 UTC by TrapJkeee

2022-05-27 04:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-29 20:29 UTC, GSemikozov requested changes

2022-05-29 20:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap');
подключаем в предназначенном для этого файле - fonts.css

2022-05-29 20:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__main {
.accordion__item

2022-05-29 20:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
жестко фиксировать ширину не стоит

2022-05-29 20:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
не хватает паддингов (их надо задать именно здесь, чтобы всем дочерним элементам не дублировать каждый раз)

2022-05-29 20:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: #212429;
цвета проставляем из переменных

2022-05-29 20:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary{
селкторы тегов в БЭМ стараемся не использовать, и если это глобальные сбросы - такие стили оформляем в normalize.css, если сброс только в контексте компонента - тогда используем БЭМ-класс

2022-06-06 07:47 UTC, TrapJkeee commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap');
"+"

2022-06-06 07:47 UTC, TrapJkeee commented on 03-lection1/02-accordion/accordion.css
> +.accordion__main {
"+"

2022-06-06 07:47 UTC, TrapJkeee commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
"+"

2022-06-06 07:47 UTC, TrapJkeee commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
"+"

2022-06-06 07:47 UTC, TrapJkeee commented on 03-lection1/02-accordion/accordion.css
> +summary{
"+"

2022-06-06 14:11 UTC, GSemikozov requested changes

2022-06-06 15:45 UTC, TrapJkeee commented on 03-lection1/02-accordion/index.html
> +            <div class="accordion__main">
"+"

2022-06-07 18:03 UTC, GSemikozov approved these changes

2022-06-07 18:03 UTC, merged