solution tooltip
js-tasks-ru/htmlcss-20220519_trapjkeeee pull request #9
Opened 2022-05-30 19:45 UTC by TrapJkeee

2022-05-30 19:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-06 14:20 UTC, GSemikozov requested changes

2022-06-06 14:20 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: 50px;
внешнее позиционирование не задаем на уровне блока

2022-06-06 14:20 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: 120%;
здесь вместо произвольных 120% советую использовать тот паттерн который мы применяли на занятии, что будет более надежно + гарантированный одинаковый отступ между иконкой и всплывашкой

2022-06-06 15:36 UTC, TrapJkeee commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: 120%;
"+"

2022-06-07 18:09 UTC, GSemikozov requested changes

2022-06-07 18:09 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: 50px;
до сих пор актуально

2022-06-09 04:30 UTC, TrapJkeee commented on 05-lection3/01-tooltip/tooltip.css
> +    top: 50px;
Опять немного не могу понять. .tooltip__item это же элемент блока .tooltip. Я элементу и задаю отступ или я что-то не так понимаю?

2022-06-09 15:37 UTC, GSemikozov requested changes

2022-06-09 15:37 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin-top:50px;
а вот не надо так)
что будет если мы встроим тултип в какой-нибудь текстовых элемент, например параграф, где ему и место? Правильно, у тултипа относительно текста будут странные отступы) так что этот элемент в целом лишний

2022-06-10 04:19 UTC, TrapJkeee commented on 05-lection3/01-tooltip/tooltip.css
> +    margin-top:50px;
Тогда вообще без отступов) Я вообще их делал, чтоб видно было на странице всплывашку, но понял что этого не нужно) "+"

2022-06-10 18:40 UTC, GSemikozov approved these changes

2022-06-10 18:40 UTC, merged